### ISSUE TITLE
No API support for .Net core?

### ISSUE THREAD

**Issue by rashmir592** [rackspace/rackspace-net-sdk#51]
I am not able to read files from RACKSPACE cloud from my .net core application, where the same code works with .net framework application, it fails in .Net core/Standard projects.                                                                                 

"errorCode": `PlatformNotSupportedException`,

"message": `Secure binary serialization is not supported on this platform.`,                                                                        

 Stack Trace: `   at System.Exception.add_SerializeObjectState(EventHandler`1 value)
   at net.openstack.Core.Exceptions.Response.ResponseException..ctor(String message, Response response)
   at net.openstack.Core.Exceptions.Response.ItemNotFoundException..ctor(Response response)
   at net.openstack.Providers.Rackspace.Validators.HttpResponseCodeValidator.Validate(Response response)
   at net.openstack.Providers.Rackspace.ProviderBase`1.CheckResponse(Response response)
   at net.openstack.Providers.Rackspace.ProviderBase`1.ExecuteRESTRequest[T](CloudIdentity identity, Uri absoluteUri, HttpMethod method, Object body, Dictionary`2 queryStringParameter, Dictionary`2 headers, Boolean isRetry, Boolean isTokenRequest, RequestSettings requestSettings, Func`7 callback)
   at net.openstack.Providers.Rackspace.ProviderBase`1.ExecuteRESTRequest(CloudIdentity identity, Uri absoluteUri, HttpMethod method, Func`3 buildResponseCallback, Object body, Dictionary`2 queryStringParameter, Dictionary`2 headers, Boolean isRetry, Boolean isTokenRequest, RequestSettings settings)
   at net.openstack.Providers.Rackspace.CloudFilesProvider.GetObject(String container, String objectName, Stream outputStream, Int32 chunkSize, Dictionary`2 headers, String region, Boolean verifyEtag, Action`1 progressUpdated, Boolean useInternalUrl, CloudIdentity identity)`

Will look forward to a quick resolution :)

Thanks in advance! :)

**Comment by chrispickford** [comment]
Please add support for .NET core. This is a major issue.

**Comment by jamsoft** [comment]
Is there no movement on this? It's not like .NET Core is new anymore.

**Comment by Caloyski** [comment]
Did they solve this?
